server:
  port: 5000

spring:
  datasource:
    url: "jdbc:h2:mem:logistica"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
  h2:
    console:
      enabled: true

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"

aws:
  access-key: "${ACCESS_KEY}"
  secret-key: "${SECRET_ACCESS_KEY}"
  region: "US-EAST-1"
  queue-name: "logistica"