name: Build and Test project

on:
  push:
    branches: [ master ]  # Runs on push to main or develop
  pull_request:
    branches: [ master ]  # Runs on pull requests to these branches

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Fetch source code

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin JDK
          java-version: '17'
          cache: 'gradle'  # Cache Gradle dependencies for speed

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # Ensure Gradle wrapper is executable

      - name: Run tests
        run: ./gradlew test

      - name: Upload Test Results
        if: always()  # Ensure reports are uploaded even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test/  # Upload test results

      - name: Build project
        run: ./gradlew clean build -x test  # Build without running tests

      - name: Package application
        run: |
          ls build/libs
          cp build/libs/logistica-api-gradle-1.0.0.jar application.jar
          zip -r app.zip application.jar

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          version_label: 4
          region: ${{ secrets.AWS_REGION }}
          deployment_package: app.zip